Load Balancer

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,33 +1,84 @@
 #!/usr/bin/env bash
-# Configures Nginx so that its HTTP response contains a custom header(on web-01 and web-2)
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-echo -e "Updating and installing Nginx.\n"
-sudo apt-get update -y -qq && \
-         sudo apt-get install nginx -y
+# uncomment to see the script run in action
+#set -x
+
+echo -e "Updating and doing some minor checks...\n"
+
+function install() {
+	command -v "$1" &> /dev/null
+
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
+
+install nginx #install nginx
 
 echo -e "\nSetting up some minor stuff.\n"
 
-# Starting Nginx service
-sudo service nginx start
-
-# Allowing Nginx on firewall
+# allowing nginx on firewall
 sudo ufw allow 'Nginx HTTP'
 
-# User ownership to website files for easy editing
-sudo chown -R "$USER":"$USER" /var/www/html
-sudo chmod -R 755 /var/www
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
 
-# Backup default index
-cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
 
-# Create new index
-echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
 
-# Add custom HTTP header to Nginx default site configuration
-echo -e "server {\n\tlisten 80;\n\tlocation / {\n\t\tadd_header X-Served-By \$host;\n\t\tinclude /etc/nginx/sites-available/default;\n\t}\n}" | sudo tee /etc/nginx/sites-available/default > /dev/null
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
 
-# Restart Nginx
-sudo service nginx restart
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
 
-echo -e "\nCompleted.  \n"
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
 
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
